MathJax.Hub.Config({
TeX: {
Macros: {
sameas: [" #1 ⇔ #2 ", 2],
ifthen: [" #1 ⇒ #2 ", 2],
onlyif: [" #1 ⇐ #2 ", 2],
mylan: [" #1 \\land #2 ", 2],
mylor: [" #1 \\lor #2 ", 2],
mynot: ["\\lnot #1 ", 1],
mysupseteq: [" #1 ⊇ #2 ", 2],
mysubseteq: [" #1 ⊆ #2 ", 2],
myne: [" #1 ≠ #2 ", 2],
myin: [" #1 ∈ #2 ", 2],
myni: [" #1 ∉ #2 ", 2],
mylt: [" #1 < #2 ", 2],
mygt: [" #1 > #2 ", 2],
myle: [" #1 ≤ #2 ", 2],
myge: [" #1 ≥ #2 ", 2],
myeq: [" #1 = #2 ", 2],
mydivi: [" #1 | #2 ", 2],
mycomma: [" #1 , #2 ", 2],
mypm: [" #1 ± #2 ", 2],
mymp: [" #1 ∓ #2 ", 2],
mydiff: [" #1 - #2 ", 2],
myplus: [" #1 + #2 ", 2],
myposinega: ["± #1 ", 1],
mynegaposi: ["∓ #1 ", 1],
mypositive: ["+ #1 ", 1],
mynegative: ["- #1 ", 1],
myoconv: [" #1 ⊛ #2 ", 2],
myoprod: [" #1 ⊙ #2 ", 2],
myoplus: [" #1 ⊕ #2 ", 2],
myomult: [" #1 ⊗ #2 ", 2],
myocirc: [" #1 ⦾ #2 ", 2],
mysprod: [" #1 ⊡ #2 ", 2],
mysplus: [" #1 ⊞ #2 ", 2],
mysmult: [" #1 ⊠ #2 ", 2],
myprod: [" #1 ⋅ #2 ", 2],
myover: [" #1 : #2 ", 2],
myrest: [" #1 \\ \\%\\  #2 ", 2],
myquot: [" #1 /\\!\\!/ #2 ", 2],
myinde: [" #1 \\| #2 ", 2],
mymult: [" #1 × #2 ", 2],
myfunc: [" #1 \\hat{} #2 ", 2],
mycirc: [" #1 ∘ #2 ", 2],
mysetminus: [" #1 ∖ #2 ", 2],
myquotient: [" #1 \\div #2 ", 2],
mycup: [" #1 ∪ #2 ", 2],
mycap: [" #1 ∩ #2 ", 2],
myeval: [" #1 \\Parenth #2 ", 2],
mynabla: ["∇ #1 ", 1],
myadjun: [" #1 ^∗", 1],
myapex: [" #1 ^ #2 ", 2],
myelem: [" #1 _ #2 ", 2],
replace: [" #1 \\!: #2 ", 2],
separat: [" #1 \\,, #2 ", 2],
defined: [" #1 \\!: #2 \\,, #3 ", 3],
myforall: ["\\forall #1 \\,,\\quad #2 ", 2],
myexists: ["\\exists #1 \\!:\\quad #2 ", 2],
Parenth: ["\\left( #1 \\right)", 1],
Bracket: ["\\left[ #1 \\right]", 1],
Curlies: ["\\left\\{ #1 \\right\\}", 1],
Modulus: ["\\left| #1 \\right|", 1],
myQuote: ["“\\  #1 \\ ”", 1],
DoubleP: ["\\left(\\!\\left( #1 \\!: #2 \\in #3 \\right)\\!\\right)", 3],
DoubleB: ["\\left[\\!\\left[ #1 \\right]\\!\\right]", 1],
DoubleC: ["\\left\\{\\!\\left\\{ #1 \\right\\}\\!\\right\\}", 1],
DoubleM: ["\\left\\| #1 \\right\\|", 1],
mybigsumm: ["\\sum_{ #1 \\in #2 } #3 ", 3],
mybigmult: ["\\mathop{\\Huge ×}_{ #1 \\in #2 } #3 ", 3],
mybigprod: ["\\prod_{ #1 \\in #2 } #3 ", 3],
mybigcap: ["\\bigcap_{ #1 \\in #2 } #3 ", 3],
mybigcup: ["\\bigcup_{ #1 \\in #2 } #3 ", 3],
mylim: ["\\lim_{ #1 \\to #2 } #3 ", 3],
goesto: [" #1 → #2 ", 2],
isfrom: [" #1 ← #2 ", 2],
Replace: ["\\left\\{ #1 \\!: #2 \\in #3 \\right\\}", 3],
Separat: ["\\left\\{ #1 \\in #2 \\,, #3 \\right\\}", 3],
Defined: ["\\left\\{ #1 \\!: #2 \\in #3 \\,, #4 \\right\\}", 4],
myllt: [" #1 < #2 < #3 ", 3],
myggt: [" #1 > #2 > #3 ", 3],
mylle: [" #1 ≤ #2 ≤ #3 ", 3],
mygge: [" #1 ≥ #2 ≥ #3 ", 3],
myeqq: [" #1 = #2 = #3 ", 3],
mylllt: [" #1 < #2 < #3 < #4 ", 4],
mygggt: [" #1 > #2 > #3 > #4 ", 4],
myllle: [" #1 ≤ #2 ≤ #3 ≤ #4 ", 4],
myggge: [" #1 ≥ #2 ≥ #3 ≥ #4 ", 4],
myeqqq: [" #1 = #2 = #3 = #4 ", 4],
mypplus: [" #1 + #2 + #3 ", 3],
mypprod: [" #1 ⋅ #2 ⋅ #3 ", 3],
myppplus: [" #1 + #2 + #3 + #4 ", 4],
myppprod: [" #1 ⋅ #2 ⋅ #3 ⋅ #4 ", 4],
MyLan: ["\\Parenth{ #1 \\land #2 }", 2],
MyLor: ["\\Parenth{ #1 \\lor #2 }", 2],
MyNot: ["\\Parenth{\\lnot #1 }", 1],
SameAs: ["\\Parenth{ #1 ⇔ #2 }", 2],
IfThen: ["\\Parenth{ #1 ⇒ #2 }", 2],
OnlyIf: ["\\Parenth{ #1 ⇐ #2 }", 2],
MyForall: ["\\Parenth{\\forall #1 \\,,\\quad #2 }", 2],
MyExists: ["\\Parenth{\\exists #1 \\!:\\quad #2 }", 2],
MyLt: ["\\Parenth{ #1 < #2 }", 2],
MyGt: ["\\Parenth{ #1 > #2 }", 2],
MyLe: ["\\Parenth{ #1 ≤ #2 }", 2],
MyGe: ["\\Parenth{ #1 ≥ #2 }", 2],
MyEq: ["\\Parenth{ #1 = #2 }", 2],
MyLlt: ["\\Parenth{ #1 < #2 < #3 }", 3],
MyGgt: ["\\Parenth{ #1 > #2 > #3 }", 3],
MyLle: ["\\Parenth{ #1 ≤ #2 ≤ #3 }", 3],
MyGge: ["\\Parenth{ #1 ≥ #2 ≥ #3 }", 3],
MyEqq: ["\\Parenth{ #1 = #2 = #3 }", 3],
MyLllt: ["\\Parenth{ #1 < #2 < #3 < #4 }", 4],
MyGggt: ["\\Parenth{ #1 > #2 > #3 > #4 }", 4],
MyLlle: ["\\Parenth{ #1 ≤ #2 ≤ #3 ≤ #4 }", 4],
MyGgge: ["\\Parenth{ #1 ≥ #2 ≥ #3 ≥ #4 }", 4],
MyEqqq: ["\\Parenth{ #1 = #2 = #3 = #4 }", 4],
MyNe: ["\\Parenth{ #1 ≠ #2 }", 2],
MyIn: ["\\Parenth{ #1 ∈ #2 }", 2],
MyNi: ["\\Parenth{ #1 ∉ #2 }", 2],
MyPlus: ["\\Parenth{ #1 + #2 }", 2],
MyProd: ["\\Parenth{ #1 ⋅ #2 }", 2],
MyPplus: ["\\Parenth{ #1 + #2 + #3 }", 3],
MyPprod: ["\\Parenth{ #1 ⋅ #2 ⋅ #3 }", 3],
MyPpplus: ["\\Parenth{ #1 + #2 + #3 + #4 }", 4],
MyPpprod: ["\\Parenth{ #1 ⋅ #2 ⋅ #3 ⋅ #4 }", 4],
MyOConv: ["\\Parenth{ #1 ⊛ #2 }", 2],
MyOProd: ["\\Parenth{ #1 ⊙ #2 }", 2],
MyOPlus: ["\\Parenth{ #1 ⊕ #2 }", 2],
MyOMult: ["\\Parenth{ #1 ⊗ #2 }", 2],
MyOCirc: ["\\Parenth{ #1 ⦾ #2 }", 2],
MySProd: ["\\Parenth{ #1 ⊡ #2 }", 2],
MySPlus: ["\\Parenth{ #1 ⊞ #2 }", 2],
MySMult: ["\\Parenth{ #1 ⊠ #2 }", 2],
MyDiff: ["\\Parenth{ #1 - #2 }", 2],
MyRest: ["\\Parenth{ #1 \\ \\%\\ #2 }", 2],
MyQuot: ["\\Parenth{ #1 /\\!\\!/ #2 }", 2],
MyInde: ["\\Parenth{ #1 \\| #2 }", 2],
MyMult: ["\\Parenth{ #1 × #2 }", 2],
MyFunc: ["\\Parenth{ #1 \\hat{} #2 }", 2],
MyCirc: ["\\Parenth{ #1 ∘ #2 }", 2],
MyCup: ["\\Parenth{ #1 ∪ #2 }", 2],
MyCap: ["\\Parenth{ #1 ∩ #2 }", 2],
MySetminus: ["\\Parenth{ #1 ∖ #2 }", 2],
MyQuotient: ["\\Parenth{ #1 / #2 }", 2],
MyBigSumm: ["\\Parenth{\\sum_{ #1 \\in #2 } #3 }", 3],
MyBigMult: ["\\Parenth{\\mathop{\\Huge ×}_{ #1 \\in #2 } #3 }", 3],
MyBigProd: ["\\Parenth{\\prod_{ #1 \\in #2 } #3 }", 3],
MyBigCap: ["\\Parenth{\\bigcap_{ #1 \\in #2 } #3 }", 3],
MyBigCup: ["\\Parenth{\\bigcup_{ #1 \\in #2 } #3 }", 3],
MyLim: ["\\Parenth{\\lim_{ #1 \\to #2 } #3 }", 3],
MyNabla: ["\\Parenth{∇ #1 }", 1],
GoesTo: ["\\Parenth{ #1 → #2 }", 2],
IsFrom: ["\\Parenth{ #1 ← #2 }", 2],
}
}
});