name: Compile LaTeX

on:
  push:
    branches:
      - main # Esegui il workflow su ogni push nella branch "main"
  pull_request: # Esegui il workflow sui pull request
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice dal repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Installa TeX Live per compilare LaTeX
    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-full latexmk

    # Compila il file LaTeX
    - name: Compile LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode -output-directory=Dispense Dispense/main.tex
        git add Dispense/main.pdf
        git commit -m "Add compiled PDF to repository"
        git push
