name: Compile LaTeX

on:
  push:
    branches:
      - main # Esegui il workflow su ogni push nella branch "main"
  pull_request: # Esegui il workflow sui pull request
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout del codice dal repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Installa TeX Live per compilare LaTeX
    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-math-extra texlive-amsfonts texlive-amsthm texlive-pictures texlive-latex-recommended texlive-babel-italian texlive-fonts-extra texlive-latex-extra latexmk    # Compila il file LaTeX

    - name: Set up Git identity
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode -output-directory=Dispense Dispense/main.tex

    - name: Push changes
      run: |
        git add Dispense/main.pdf
        git commit -m "Add compiled PDF to repository"
        git push https://x-access-token:${{ secrets.TokenForBots }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}